package craft.app.models;

import javax.persistence.*;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Represents the User object which is stored in the database and contains all of the
 * attributes of a user.
 */
@Entity
public class User {
    
    /**
     * An autogenerated number which acts as the primary key in the database
     */
    @Id
    @GeneratedValue
    @Column(nullable = false, length = 10)
    private Long userId;
    
    /**
     * The user's username, must be unique
     */
    @Column(unique = true, nullable = false)
    private String username;
    
    /**
     * The user's email address
     */
    private String email;
    
    /**
     * The user's password, encrypted
     */
    @Column(nullable = false)
    private String password;
    
    
    
    /**
     * When seeding the database, users are created with parameters set, so this method is
     *      * used, which first creates an empty user and then sets the variables
     * @param username
     * @param password
     * @param email
     */
    public User(String username, String password, String email) {
        this();
        this.username = username;
        this.password = password;
        this.email = email;
    }

    protected User() {
    }
    
   
    
    public String getUsername() {
        return username;
    }

    public String getEmail() {
        return email;
    }
    
    
    public Long getUserId(){
        return userId;
    }
    
    public String getPassword() {
        return password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
}
