# Used while setting up and testing the APIs




# API LISTING MANAGEMENT

GET {{host-url}}/projects


###

POST {{host-url}}/projects
Content-Type: application/json


{
  "title": "Bore another Added",
  "description": "Yet more Project Description",
  "type": "sewing",
"creator": {
  "username": "Sarah",
  "location": "Hamilton",
  "email": "new@test.com"
}
}
###


POST {{host-url}}/users
Content-Type: application/json


{

  "username": "Sarah",
  "password": "sarah123",
  "email": "new@test.com"

}

###

POST {{host-url}}/login
Content-Type: application/json

{
"username": "user",
"password": "password"
}

###

DELETE {{host-url}}/projects/5
Authorization: Basic Ym9iOmJvYjEyMw==

###

