# For a quick start check out our HTTP Requests collection (Tools|HTTP User|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);





# API LISTING MANAGEMENT

GET {{host-url}}/projects

###

#GET {{host-url}}//listings/type/sewing

###

#GET {{host-url}}//listings/location/Hamilton

###

POST {{host-url}}/projects
Content-Type: application/json
Authorization: Basic Ym9iOmJvYjEyMw==


{
  "title": "Bore another Added",
  "description": "Yet more Project Description",
  "type": "sewing",
"creator": {
  "name": "Sarah",
  "location": "Hamilton",
  "email": "new@test.com"
}
}
###

POST {{host-url}}/login
Content-Type: application/json

{
"username": "user",
"password": "password"
}

###

DELETE {{host-url}}/projects/5
Authorization: Basic Ym9iOmJvYjEyMw==

###

